#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""R2-R7 数据扩充（T001，用户已授权全量）。

按统一路线 skill §2/§3 把 capsule 数据从 20 条扩充到 100 档（80 train + 20 fresh），
并生成 state_patch 验证集 30-50 条。

来源（优先级）：
  1. 现有 pool 20 条（real 12 + manual 8）—— proven: existing
  2. 工作区外真实材料（金融模型及数据：三策略看板多版本、回测报告、策略备份）—— proven: external_real
  3. 轨迹挖掘（dispatcher.log / 任务账本 396 条）—— proven: trajectory
  4. derived（anchor_derived 72 筛选）—— proven: derived
  5. 人工构造（按 STALE/t0_t1 失败模式）—— proven: manual

输出：
  - data/r3/ec_v1/data100/train_capsule.jsonl（80 条，task_type=capsule）
  - data/r3/ec_v1/data100/fresh_capsule.jsonl（20 条，task_type=capsule）
  - data/r3/ec_v1/data100/state_patch_validation.jsonl（30-50 条，task_type=state_patch）
  - data/r3/ec_v1/data100/manifest.json（来源/分层/task_type 记录）

约束：
  - 不修改 models/_archive/ 冻结资产
  - 不修改 QXEN_R2_R7_UNIFIED_ROUTE_SKILL.md
  - 外部材料只读（不修改金融模型及数据）
  - fresh 与 train 零重叠，fresh 只用真实锚点（不用扩增样本充数）
"""
from __future__ import annotations

import json
import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "data/r3/ec_v1/data100"

# 现有 pool
POOL = ROOT / "data/r3/ec_v1/pool/ec_v1_pool.jsonl"
# 外部真实材料锚点（手工收集自金融模型及数据，只读）
EXTERNAL_ANCHORS = [
    {
        "anchor_id": "EXT-01",
        "source_type": "code",
        "candidate_path": "~/Desktop/金融模型及数据/0 python/02 源码_策略/三策略每日看板/三策略每日看板.py",
        "evidence_excerpt": "铨熙资本行情看板：潮金牛马正式版Top5 × 鎏金独行Top5 × 先胜待机。每日早上 11:00 运行。",
        "event_date": "2026-08-10",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["两策略版归档: 2026-08-07", "三策略版发布: 2026-08-10"],
        "authority": "T1",
        "provenance": "external_real",
    },
    {
        "anchor_id": "EXT-02",
        "source_type": "code",
        "candidate_path": "~/Desktop/金融模型及数据/0 python/02 源码_策略/三策略每日看板/三策略每日看板.py.bak_两策略改现金鎏金",
        "evidence_excerpt": "两策略版备份：两策略改现金鎏金。",
        "event_date": "2026-08-07",
        "as_of": "2026-08-14",
        "operative_status": "SUPERSEDED",
        "timeline": ["两策略改现金鎏金版: 2026-08-07 归档", "三策略版取代: 2026-08-10"],
        "authority": "T4",
        "provenance": "external_real",
    },
    {
        "anchor_id": "EXT-03",
        "source_type": "code",
        "candidate_path": "~/Desktop/金融模型及数据/0 python/02 源码_策略/三策略每日看板/三策略每日看板.py.bak_点金双擎",
        "evidence_excerpt": "点金双擎版备份（更早版本）。",
        "event_date": "2026-08-07",
        "as_of": "2026-08-14",
        "operative_status": "SUPERSEDED",
        "timeline": ["点金双擎版: 2026-08-07 归档", "三策略版取代: 2026-08-10"],
        "authority": "T4",
        "provenance": "external_real",
    },
    {
        "anchor_id": "EXT-04",
        "source_type": "report",
        "candidate_path": "~/Desktop/金融模型及数据/回测/冬藏v11_供需错配产能优化_AB验证/冬藏v10.2_vs_v11_净值回撤.png",
        "evidence_excerpt": "冬藏 v10.2 vs v11 供需错配产能优化 AB 验证净值回撤对比图。",
        "event_date": "2026-08-11",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["冬藏 v10.2: 旧版", "冬藏 v11: 2026-08-11 AB 验证"],
        "authority": "T3",
        "provenance": "external_real",
    },
    {
        "anchor_id": "EXT-05",
        "source_type": "report",
        "candidate_path": "~/Desktop/金融模型及数据/回测/三策略等权_现金牛马正式非主动去库_鎏金_先胜_2006-2026/四窗口净值回撤图/三策略四窗口净值回撤看板.html.bak_20260730_15bp",
        "evidence_excerpt": "三策略四窗口净值回撤看板 HTML 备份（2026-07-30 15bp）。",
        "event_date": "2026-07-30",
        "as_of": "2026-08-14",
        "operative_status": "SUPERSEDED",
        "timeline": ["HTML 看板备份: 2026-07-30", "后续版本取代"],
        "authority": "T4",
        "provenance": "external_real",
    },
    {
        "anchor_id": "EXT-06",
        "source_type": "report",
        "candidate_path": "~/Desktop/金融模型及数据/宏观六象限_股债商统计显著性_v5.15_通缩边界实验版.html",
        "evidence_excerpt": "宏观六象限股债商统计显著性 v5.15 通缩边界实验版报告。",
        "event_date": "2026-08-12",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["v5.15 通缩边界实验版: 最新"],
        "authority": "T3",
        "provenance": "external_real",
    },
    {
        "anchor_id": "EXT-07",
        "source_type": "data_file",
        "candidate_path": "~/Desktop/金融模型及数据/回测/中观产能周期模型_非金融_v58.xlsx",
        "evidence_excerpt": "中观产能周期模型非金融版 v58。",
        "event_date": "2026-08-12",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["产能周期模型 v58: 最新"],
        "authority": "T1",
        "provenance": "external_real",
    },
    {
        "anchor_id": "EXT-08",
        "source_type": "data_file",
        "candidate_path": "~/Desktop/金融模型及数据/回测/中观产能周期模型_非金融_v58（创业板）.xlsx",
        "evidence_excerpt": "中观产能周期模型非金融版 v58 创业板变体（同版本不同市场切片）。",
        "event_date": "2026-08-12",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["v58 主模型: 2026-08-12", "v58 创业板切片: 同时"],
        "authority": "T1",
        "provenance": "external_real",
    },
]


def load_jsonl(path: Path) -> list[dict]:
    if not path.is_file():
        return []
    return [json.loads(l) for l in path.read_text(encoding="utf-8").splitlines() if l.strip()]


# 轨迹挖掘 capsule 样本（从任务账本提炼的"证据-效力判定"对，人工审核后固化）
# 每条含：候选来源 + 证据摘录 + 效力判定（CURRENT/SUPERSEDED/STALE）+ 权威层级
TRAJECTORY_CAPSULES = [
    {
        "anchor_id": "TRJ-001",
        "source_type": "config",
        "candidate_path": "configs/lora_ctxA.yaml",
        "evidence_excerpt": "T002 Dispatcher 配置修复验证：dispatcher_health=OK(deepseek-v4-flash)。",
        "event_date": "2026-08-12",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["配置修复验证: 2026-08-12", "状态生效: 当前"],
        "authority": "T1",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-002",
        "source_type": "data_file",
        "candidate_path": "data/real_samples.jsonl",
        "evidence_excerpt": "T009 真实训练数据准备：从 8 个本地文件(1995行)生成 data/real_samples.jsonl(115条 instruct)。",
        "event_date": "2026-08-12",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["真实数据生成: 2026-08-12", "状态生效: 当前"],
        "authority": "T1",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-003",
        "source_type": "model_weights",
        "candidate_path": "outputs/lora_adapters_r1_recall/adapters.safetensors",
        "evidence_excerpt": "T058 QXEN 状态确认：R1 正式产物 outputs/lora_adapters_r1_selected/ 存在(adapters.safetensors 10.8MB)。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["R1 正式产物: 2026-08-13", "门控指标 PASS: acc=0.8148"],
        "authority": "T1",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-004",
        "source_type": "model_weights",
        "candidate_path": "outputs/lora_adapters_r1_recall/0000050_adapters.safetensors",
        "evidence_excerpt": "R1 recall 训练的周期 checkpoint（iter 50），后被最终权重取代。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "SUPERSEDED",
        "timeline": ["周期 checkpoint iter50: 2026-08-13", "最终权重取代: 同日晚些"],
        "authority": "T4",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-005",
        "source_type": "data_file",
        "candidate_path": "data/hq1700/train_formatted.jsonl",
        "evidence_excerpt": "T051 HQ1700 高质量数据集重训：1700 条 7 标签均衡，训练 500 iters loss 4.51→1.31，但门控 FAIL。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "SUPERSEDED",
        "timeline": ["HQ1700 数据集: 2026-08-13 构建", "门控 FAIL: 被 T052 混合训练取代"],
        "authority": "T1",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-006",
        "source_type": "data_file",
        "candidate_path": "data/mixed_train/train.jsonl",
        "evidence_excerpt": "T052 混合训练修复 HQ1700 分布偏移并重新门控 PASS（正式产物）：477 条=HQ1700 抽取 400 + balanced 78。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["混合训练: 2026-08-13", "门控 PASS: 正式产物"],
        "authority": "T1",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-007",
        "source_type": "data_file",
        "candidate_path": "data/phaseB/train.jsonl",
        "evidence_excerpt": "T054 Phase B 门控评估 FAIL，按 Dispatcher 决策回退选项 A(mixed 为正式产物)，phaseB 冻结。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "SUPERSEDED",
        "timeline": ["phaseB 训练: 2026-08-13", "门控 FAIL 冻结: 回退 mixed"],
        "authority": "T1",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-008",
        "source_type": "data_file",
        "candidate_path": "data/distill_ctxA/train_balanced.jsonl",
        "evidence_excerpt": "T049 修正 DROP 过度占比并重训 adapter：平衡数据 108→78 条(DROP 45.4%→24.4%)。",
        "event_date": "2026-08-12",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["DROP 过度修正: 2026-08-12", "重训 adapter: 平衡版"],
        "authority": "T1",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-009",
        "source_type": "report",
        "candidate_path": "reports/r3/r3a_synthetic_freeze.md",
        "evidence_excerpt": "R3A 合成主线冻结报告：v5 LoRA 对 STALE 负迁移(35%→15.6%)，合成路线失效。",
        "event_date": "2026-08-14",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["合成主线冻结: 2026-08-14", "状态生效: 当前"],
        "authority": "T3",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-010",
        "source_type": "model_weights",
        "candidate_path": "models/r3a_cot_v5/adapters.safetensors",
        "evidence_excerpt": "R3A v5 adapter 冻结：operative=0.510，STALE 15.6%，Gate FAIL。",
        "event_date": "2026-08-14",
        "as_of": "2026-08-14",
        "operative_status": "SUPERSEDED",
        "timeline": ["v5 训练: 2026-08-13", "Gate FAIL 冻结: 2026-08-14 不再 resume"],
        "authority": "T1",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-011",
        "source_type": "model_weights",
        "candidate_path": "models/ec_v1/adapters.safetensors",
        "evidence_excerpt": "ec_v1 训练 40 iters/20 条：19/20 parse = 过拟合假象，归档为 T001 快照。",
        "event_date": "2026-08-14",
        "as_of": "2026-08-14",
        "operative_status": "SUPERSEDED",
        "timeline": ["ec_v1 训练: 2026-08-14", "过拟合判定归档: 同日"],
        "authority": "T3",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-012",
        "source_type": "doc",
        "candidate_path": "QXEN_R2_R7_UNIFIED_ROUTE_SKILL.md",
        "evidence_excerpt": "统一路线 skill：单 adapter qxen_joint_v1 + task_type 分流 + 双层 Gate（Kimi-Expert redefine）。",
        "event_date": "2026-08-15",
        "as_of": "2026-08-15",
        "operative_status": "CURRENT",
        "timeline": ["统一路线 skill: 2026-08-15", "取代旧 7 阶段范式"],
        "authority": "T2",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-013",
        "source_type": "doc",
        "candidate_path": "QXEN_R2_R7_LEGAL_ELEMENT_TRAINING_SKILL.md",
        "evidence_excerpt": "旧 7 阶段范式 skill（3000条/阶段独立 adapter），被统一路线 skill 取代。",
        "event_date": "2026-08-15",
        "as_of": "2026-08-15",
        "operative_status": "SUPERSEDED",
        "timeline": ["旧 skill: 2026-08-14 前有效", "统一路线取代: 2026-08-15"],
        "authority": "T2",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-014",
        "source_type": "model_weights",
        "candidate_path": "outputs/lora_adapters_safe/adapters.safetensors",
        "evidence_excerpt": "T031 第十次 LoRA 训练（500 iters）验收 PASS，配置 v11 收敛推进。",
        "event_date": "2026-08-12",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["安全配置训练: 2026-08-12", "500 iters 收敛 PASS"],
        "authority": "T1",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-015",
        "source_type": "config",
        "candidate_path": "configs/lora_train_ctxA_v11.yaml",
        "evidence_excerpt": "T037 Step C: grad_accumulation_steps 1→4 完整训练 550 iters，final train loss 0.685。",
        "event_date": "2026-08-12",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["Step C 训练: 2026-08-12", "状态生效"],
        "authority": "T1",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-016",
        "source_type": "config",
        "candidate_path": "configs/lora_train_ctxA_v12.yaml",
        "evidence_excerpt": "T038 Step D: learning_rate 1e-5→5e-6 完整训练 550 iters，final train loss 0.972。",
        "event_date": "2026-08-12",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["Step D 训练: 2026-08-12", "状态生效"],
        "authority": "T1",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-017",
        "source_type": "doc",
        "candidate_path": "logs/panic-full-2026-08-12-184548.0002.panic",
        "evidence_excerpt": "T019 训练中整机自动关机原因排查：内核 panic 非正常关机；T020 落地内存保护配置与监控脚本。",
        "event_date": "2026-08-12",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["内核 panic: 2026-08-12 18:45", "防复发落地: 同日"],
        "authority": "T3",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-018",
        "source_type": "data_file",
        "candidate_path": "data/train_augA.jsonl",
        "evidence_excerpt": "T040 过采样数据增强：中文文档/规则类 19 条 2x 过采样，92→111 条，v16 配置 rank4 基线。",
        "event_date": "2026-08-12",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["过采样增强: 2026-08-12", "rank4 基线重跑"],
        "authority": "T1",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-019",
        "source_type": "data_file",
        "candidate_path": "data/rewrite_variants.jsonl",
        "evidence_excerpt": "T041 方案B LLM 同义改写：19 条 doc 样本生成 37 个改写变体，相似度<0.95 全通过。",
        "event_date": "2026-08-12",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["改写变体: 2026-08-12", "校验通过"],
        "authority": "T1",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-020",
        "source_type": "report",
        "candidate_path": "reports/T043_final_report.md",
        "evidence_excerpt": "T042/T043 实际 QXEN Agent 端到端能力评估：本轮 LoRA 训练未达 v1.0 生产标准，最佳 rank4/iter450=1.4135。",
        "event_date": "2026-08-12",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["端到端评估: 2026-08-12", "结论: 未达生产标准"],
        "authority": "T3",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-021",
        "source_type": "data_file",
        "candidate_path": "outputs/context_decision_dataset/train.jsonl",
        "evidence_excerpt": "T045 Phase A 数据集构建：108 条 Context Decision 样本（distractor=26/selection=21/distill=41/drop=20）。",
        "event_date": "2026-08-12",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["Phase A 数据集: 2026-08-12", "状态生效"],
        "authority": "T1",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-022",
        "source_type": "model_weights",
        "candidate_path": "outputs/lora_adapters_ctxA/adapters.safetensors",
        "evidence_excerpt": "T047 ctxA adapter 训练完成（108 条）。",
        "event_date": "2026-08-12",
        "as_of": "2026-08-14",
        "operative_status": "SUPERSEDED",
        "timeline": ["ctxA 训练: 2026-08-12", "T049 balanced 重训取代"],
        "authority": "T1",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-023",
        "source_type": "report",
        "candidate_path": "reports/T048_heldout_eval.md",
        "evidence_excerpt": "T048 Phase A held-out 评估（193 条）：MODEL REGRESSION，ctxA 4 指标均未超 base（accuracy 0.1451 vs 0.1）。",
        "event_date": "2026-08-12",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["held-out 评估: 2026-08-12", "结论: MODEL REGRESSION"],
        "authority": "T3",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-024",
        "source_type": "model_weights",
        "candidate_path": "models/qxen_context_policy_HQ600_final/adapters.safetensors",
        "evidence_excerpt": "T050 HQ600 高质量 Context Policy 数据第一层训练完成（7 标签均衡 85-86/类，DROP 14.3%）。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["HQ600 训练: 2026-08-13", "状态生效"],
        "authority": "T1",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-025",
        "source_type": "report",
        "candidate_path": "reports/r1_base_benchmark.md",
        "evidence_excerpt": "T055 QXEN-CD R1 Base benchmark：rel/irrel 二分类，base 无 adapter，test.jsonl 540 条。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["R1 Base 基准: 2026-08-13", "状态生效"],
        "authority": "T3",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-026",
        "source_type": "config",
        "candidate_path": "configs/qxen_cd_r1_train.yaml",
        "evidence_excerpt": "T056 QXEN-CD R1 训练准备：模型/数据/超参/输出配置完成，scripts/train_qxen_cd_r1.sh 语法 OK。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["R1 训练准备: 2026-08-13", "状态生效"],
        "authority": "T1",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-027",
        "source_type": "model_weights",
        "candidate_path": "outputs/lora_adapters_r1_selected/adapters.safetensors",
        "evidence_excerpt": "T057 QXEN-CD R1 完整训练+门控：v1(1:2,500iters) FAIL acc0.8074，v2(1:1,1440条+valid早停) 通过门控为正式产物。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["v1 FAIL: 2026-08-13", "v2 门控 PASS: 正式产物"],
        "authority": "T1",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-028",
        "source_type": "data_file",
        "candidate_path": "data/r1_recall_repair/train_3000.jsonl",
        "evidence_excerpt": "T339 r1_selected 已冻结，生成 3000 条 Recall-Repair 数据。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["r1_selected 冻结: 2026-08-13", "3000 条 Recall-Repair"],
        "authority": "T1",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-029",
        "source_type": "data_file",
        "candidate_path": "data/r1_recall_repair/replay.jsonl",
        "evidence_excerpt": "T340 从 train.jsonl(1440) 经 ground_truth 映射构建 720 条 replay（hard_negative 215/direct_rel 360）。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["replay 构建: 2026-08-13", "720 条"],
        "authority": "T1",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-030",
        "source_type": "log",
        "candidate_path": "logs/r11_training_resume.log",
        "evidence_excerpt": "T341 R1.1 训练：首轮 iter1015 内存 SIGTERM → resume 1880 iters 总 2880，正常退出。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["首轮 SIGTERM: 2026-08-13", "resume 完成"],
        "authority": "T3",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-031",
        "source_type": "report",
        "candidate_path": "reports/R1.1_TEST_REPORT.md",
        "evidence_excerpt": "T342 R1.1 fresh untouched test 评估：全指标 1.0（540/540，False IRREL=0/False REL=0/invalid=0）。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["fresh test 评估: 2026-08-13", "全指标 1.0"],
        "authority": "T3",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-032",
        "source_type": "report",
        "candidate_path": "reports/r11_shadow_eval.md",
        "evidence_excerpt": "T343 Shadow 阶段：R1.1 ckpt 在 8 条真实元素场景 accuracy 0.625，3 例 False REL（含数据泄漏级误判），False IRREL=0。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["Shadow 评估: 2026-08-13", "数据内满分 vs 真实 0.625"],
        "authority": "T3",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-033",
        "source_type": "data_file",
        "candidate_path": "data/r1.2/train_all.jsonl",
        "evidence_excerpt": "T348 R1.2 数据合并：train_all 420 条（sha256 e5ac70ec）+ valid_all 20 条，清单可追溯。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["R1.2 数据合并: 2026-08-13", "420+20 sha256"],
        "authority": "T1",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-034",
        "source_type": "log",
        "candidate_path": "logs/memory_guard_block.log",
        "evidence_excerpt": "T350 R3 内存守卫触发禁止训练：--check-config 23/23 PASS 但 vm_stat Pages free 仅 102-136MB << 500MB 硬阈值。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["内存守卫 BLOCKED: 2026-08-13", "释放内存后恢复"],
        "authority": "T3",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-035",
        "source_type": "report",
        "candidate_path": "reports/r3/gate_fail_r3_v1.md",
        "evidence_excerpt": "T352 R3 Gate FAIL（5/7 未达标）：Fresh Test 540 条 status_acc0.5148/authority_acc0.3444/superseded_rej0.0。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["R3 Gate FAIL: 2026-08-13", "转 R3A/R3B/R3C 拆分"],
        "authority": "T3",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-036",
        "source_type": "data_file",
        "candidate_path": "data/r3/mlx_fixed/train.jsonl",
        "evidence_excerpt": "T353 格式修复+重训（train2160/valid300）但 gate 仍 FAIL，数据冻结作基线。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "SUPERSEDED",
        "timeline": ["格式修复重训: 2026-08-13", "gate 仍 FAIL 冻结"],
        "authority": "T1",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-037",
        "source_type": "report",
        "candidate_path": "reports/R1.3_B4_FINAL.md",
        "evidence_excerpt": "T357 R1.3 B4 最终评估（CLOSED）：θ=0.4 logit 规则 valid 20 acc=1.0(FR0/FI0)，Shadow 5 acc=1.0。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["R1.3 B4: 2026-08-13", "θ=0.4 acc=1.0 CLOSED"],
        "authority": "T3",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-038",
        "source_type": "data_file",
        "candidate_path": "data/r1.4/label_review.json",
        "evidence_excerpt": "T361 R1.4 DECISION 选项 D：严格证据口径标签复核，TR-05(评估报告=输出产物) REL→IRREL 等修正。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["标签复核: 2026-08-13", "严格证据口径"],
        "authority": "T1",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-039",
        "source_type": "report",
        "candidate_path": "docs/R15_CLOSURE_REPORT.md",
        "evidence_excerpt": "T368 R1.5 收尾闭环：总评估 39 条 acc=1.0 FR0 FI0，性能占比 0.0042%，跨域泛化 8/8。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["R1.5 闭环: 2026-08-13", "acc=1.0 稳定"],
        "authority": "T3",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-040",
        "source_type": "data_file",
        "candidate_path": "data/r1.8/train_twoline.jsonl",
        "evidence_excerpt": "T378 R1.8 方案C 关闭：v1(36条2:1) FAIL acc0.6456，v2(48条1:1 平衡) 完成关闭。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["v1 FAIL: 2026-08-13", "v2 平衡关闭"],
        "authority": "T1",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-041",
        "source_type": "report",
        "candidate_path": "reports/r1.9/closure_report.md",
        "evidence_excerpt": "T379 R1.9 全链路收尾：冻结资产 28 项 SHA256 核验全 OK（0 MISSING/0 MISMATCH）。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["R1.9 收尾: 2026-08-13", "28 项 SHA256 全 OK"],
        "authority": "T3",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-042",
        "source_type": "data_file",
        "candidate_path": "data/r3/tr_family_all.jsonl",
        "evidence_excerpt": "R3 数据族1-8 构建：累计 3000 行（train2160/valid300/fresh540=72/10/18），validate PASS。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "SUPERSEDED",
        "timeline": ["R3 数据构建: 2026-08-13", "合成主线冻结后作基线"],
        "authority": "T1",
        "provenance": "trajectory",
    },
    {
        "anchor_id": "TRJ-043",
        "source_type": "data_file",
        "candidate_path": "data/r3/staging/r3a/train.jsonl",
        "evidence_excerpt": "R3A/R3B/R3C 拆分训练 pipeline 构建：r3a(720×3)/r3b(432×5)/r3c(1080×2) 平衡数据。",
        "event_date": "2026-08-14",
        "as_of": "2026-08-14",
        "operative_status": "SUPERSEDED",
        "timeline": ["拆分 pipeline: 2026-08-14", "统一路线取代"],
        "authority": "T1",
        "provenance": "trajectory",
    },
]


# derived 样本：从 anchor_derived 可逆推的 capsule 任务（真实时间线数据派生的效力判定）
DERIVED_ANCHORS = [
    {
        "anchor_id": "DRV-001",
        "source_type": "data_file",
        "candidate_path": "data/r1_balanced/train.jsonl",
        "evidence_excerpt": "R1 平衡训练数据，用于 replay 构建。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["R1 平衡数据: 2026-08-13", "replay 构建输入"],
        "authority": "T1",
        "provenance": "derived",
    },
    {
        "anchor_id": "DRV-002",
        "source_type": "data_file",
        "candidate_path": "data/r1_recall_repair/test_fresh.jsonl",
        "evidence_excerpt": "R1 fresh test 冻结 540 条 (sha256 9989b7b3)，评估专用不得进入 replay。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["fresh test 冻结: 2026-08-13", "评估专用"],
        "authority": "T1",
        "provenance": "derived",
    },
    {
        "anchor_id": "DRV-003",
        "source_type": "report",
        "candidate_path": "reports/R1.1_TEST_REPORT.md",
        "evidence_excerpt": "R1.1 评估报告：全指标 1.0000 (540/540)。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["R1.1 评估: 2026-08-13", "r11 全指标 1.0000"],
        "authority": "T3",
        "provenance": "derived",
    },
    {
        "anchor_id": "DRV-004",
        "source_type": "report",
        "candidate_path": "reports/R1.2_FINAL_EVALUATION.md",
        "evidence_excerpt": "R1.2 最终评估报告（ELEMENT-AWARE MATERIALITY REPAIR）。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["R1.2 评估: 2026-08-13", "最终评估"],
        "authority": "T3",
        "provenance": "derived",
    },
    {
        "anchor_id": "DRV-005",
        "source_type": "doc",
        "candidate_path": "docs/R1.3_PLAN.md",
        "evidence_excerpt": "R1.3 规划文档（下一阶段计划）。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["R1.3 规划: 2026-08-13"],
        "authority": "T2",
        "provenance": "derived",
    },
    {
        "anchor_id": "DRV-006",
        "source_type": "env_check",
        "candidate_path": "logs/env_check.md",
        "evidence_excerpt": "环境检查文档（运行环境核验记录）。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["环境检查: 2026-08-13"],
        "authority": "T3",
        "provenance": "derived",
    },
    {
        "anchor_id": "DRV-007",
        "source_type": "log",
        "candidate_path": "logs/r11_training_resume.log",
        "evidence_excerpt": "R1 recall 训练日志（resume）。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["训练日志: 2026-08-13"],
        "authority": "T3",
        "provenance": "derived",
    },
    {
        "anchor_id": "DRV-008",
        "source_type": "data_file",
        "candidate_path": "data/r1_recall_repair/train_new.jsonl",
        "evidence_excerpt": "R1 recall 修复训练数据（补充样本）。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["训练数据: 2026-08-13"],
        "authority": "T1",
        "provenance": "derived",
    },
    {
        "anchor_id": "DRV-009",
        "source_type": "config",
        "candidate_path": "outputs/lora_adapters_r1_recall/adapter_config.json",
        "evidence_excerpt": "R1 recall adapter 配置快照（iters=1880, resume 0001000）。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["配置快照: 2026-08-13"],
        "authority": "T1",
        "provenance": "derived",
    },
    {
        "anchor_id": "DRV-010",
        "source_type": "data_file",
        "candidate_path": "data/r3/ec_v1/pool/ec_v1_pool.jsonl",
        "evidence_excerpt": "ec_v1 pool 20 条证据胶囊（真实锚点 12 + 人工标注 8）。",
        "event_date": "2026-08-14",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["pool 构建: 2026-08-14", "契约 evidence_capsule_v1"],
        "authority": "T1",
        "provenance": "derived",
    },
    {
        "anchor_id": "DRV-011",
        "source_type": "config",
        "candidate_path": "configs/evidence_capsule_v1_schema.json",
        "evidence_excerpt": "evidence_capsule_v1 契约 schema（外层固定 JSON + 内层自然语言）。",
        "event_date": "2026-08-14",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["契约 schema: 2026-08-14"],
        "authority": "T2",
        "provenance": "derived",
    },
    {
        "anchor_id": "DRV-012",
        "source_type": "report",
        "candidate_path": "reports/r3/transition_baseline_v5_field_eval.json",
        "evidence_excerpt": "v5 旧 eval_set 540 条基线：operative=0.676, conflict=0.694, authority=0.878。",
        "event_date": "2026-08-14",
        "as_of": "2026-08-14",
        "operative_status": "SUPERSEDED",
        "timeline": ["v5 基线评估: 2026-08-14", "契约切换后作参考"],
        "authority": "T3",
        "provenance": "derived",
    },
    {
        "anchor_id": "DRV-013",
        "source_type": "report",
        "candidate_path": "reports/r3/gate_conflict_hide_threshold.md",
        "evidence_excerpt": "显式冲突≤0.05 / 隐含冲突≤0.30 过渡 / 可追溯≥0.95 Gate 阈值。",
        "event_date": "2026-08-14",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["Gate 阈值定义: 2026-08-14"],
        "authority": "T2",
        "provenance": "derived",
    },
    {
        "anchor_id": "DRV-014",
        "source_type": "data_file",
        "candidate_path": "data/r3/ec_v1/manual/manual_annotations.jsonl",
        "evidence_excerpt": "ec_v1 人工标注 8 条（含 TR-06 SUPERSEDED 链，三类稀缺模式齐全）。",
        "event_date": "2026-08-14",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["人工标注: 2026-08-14", "8 锚点覆盖"],
        "authority": "T1",
        "provenance": "derived",
    },
    {
        "anchor_id": "DRV-015",
        "source_type": "log",
        "candidate_path": "日志/dispatcher.log",
        "evidence_excerpt": "Dispatcher 任务分发日志（148 去重 goal，1206 事件行）。",
        "event_date": "2026-08-14",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["Dispatcher 运行日志: 持续"],
        "authority": "T3",
        "provenance": "derived",
    },
]


# 人工构造 capsule 样本（按 STALE / t0_t1 失败模式定向补齐）
MANUAL_CAPSULES = [
    {
        "anchor_id": "MAN-001",
        "source_type": "config",
        "candidate_path": "configs/lora_train_safe.yaml.bak_v4",
        "evidence_excerpt": "lora_train_safe.yaml 备份 v4（已归档备份配置，非当前活跃配置）。",
        "event_date": "2026-08-10",
        "as_of": "2026-08-14",
        "operative_status": "STALE",
        "timeline": ["备份配置归档: 2026-08-10", "当前活跃: 非此文件"],
        "authority": "T4",
        "provenance": "manual",
    },
    {
        "anchor_id": "MAN-002",
        "source_type": "data_file",
        "candidate_path": "data/r3/r3a_gate_test_ext/eval_pool.jsonl",
        "evidence_excerpt": "r3a gate test ext eval_pool 192 条（v6 标注版，R3A 冻结资产）。",
        "event_date": "2026-08-14",
        "as_of": "2026-08-14",
        "operative_status": "STALE",
        "timeline": ["R3A gate test: 2026-08-13", "合成主线冻结: 2026-08-14 不再使用"],
        "authority": "T1",
        "provenance": "manual",
    },
    {
        "anchor_id": "MAN-003",
        "source_type": "report",
        "candidate_path": "reports/r3/r3a_realistic_gate_v5_pool_v6.json",
        "evidence_excerpt": "R3A v5 pool v6 评估报告（operative=0.547，STALE 15.6%）。",
        "event_date": "2026-08-14",
        "as_of": "2026-08-14",
        "operative_status": "STALE",
        "timeline": ["v5 pool v6 评估: 2026-08-14", "冻结作基线"],
        "authority": "T3",
        "provenance": "manual",
    },
    {
        "anchor_id": "MAN-004",
        "source_type": "model_weights",
        "candidate_path": "models/r3a_cot_v4/adapters.safetensors",
        "evidence_excerpt": "R3A cot v4 adapter（v5 前代，字段隔离契约基线）。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "SUPERSEDED",
        "timeline": ["v4 训练: 2026-08-13", "v5 取代: 2026-08-14"],
        "authority": "T1",
        "provenance": "manual",
    },
    {
        "anchor_id": "MAN-005",
        "source_type": "config",
        "candidate_path": "configs/r3a_cot_v4.yaml",
        "evidence_excerpt": "r3a_cot_v4 训练配置（legacy 契约：reason_code 打包判定）。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "SUPERSEDED",
        "timeline": ["v4 配置: 2026-08-13", "字段隔离契约取代: v5"],
        "authority": "T2",
        "provenance": "manual",
    },
    {
        "anchor_id": "MAN-006",
        "source_type": "data_file",
        "candidate_path": "data/r3/ec_v1/pred/ec_v1_pred_capsules.jsonl",
        "evidence_excerpt": "ec_v1 推理 19/20 parse（过拟合假象产物）。",
        "event_date": "2026-08-14",
        "as_of": "2026-08-14",
        "operative_status": "STALE",
        "timeline": ["ec_v1 推理: 2026-08-14", "判定过拟合: 归档"],
        "authority": "T3",
        "provenance": "manual",
    },
    {
        "anchor_id": "MAN-007",
        "source_type": "model_weights",
        "candidate_path": "models/r3a_hard_pure_v1/adapters.safetensors",
        "evidence_excerpt": "R3A hard pure v1 adapter（合成纯硬负样本路线）。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "SUPERSEDED",
        "timeline": ["hard pure v1: 2026-08-13", "合成主线冻结: 2026-08-14"],
        "authority": "T1",
        "provenance": "manual",
    },
    {
        "anchor_id": "MAN-008",
        "source_type": "doc",
        "candidate_path": "调度状态/STATE_baseline.md",
        "evidence_excerpt": "任务调度体系状态基线（Phase A ctxA mixed PASS / Phase B 冻结 FAIL / Phase R1）。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["状态基线: 2026-08-13", "当前状态基准"],
        "authority": "T2",
        "provenance": "manual",
    },
    {
        "anchor_id": "MAN-009",
        "source_type": "model_weights",
        "candidate_path": "outputs/lora_adapters_ctxA_balanced/adapters.safetensors",
        "evidence_excerpt": "T049 ctxA balanced adapter（DROP 占比修正后重训）。",
        "event_date": "2026-08-12",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["DROP 修正重训: 2026-08-12", "状态生效"],
        "authority": "T1",
        "provenance": "manual",
    },
    {
        "anchor_id": "MAN-010",
        "source_type": "data_file",
        "candidate_path": "data/distill_ctxA/train_before_balancing.jsonl",
        "evidence_excerpt": "T049 修正前 ctxA 数据（DROP 45.4% 过度占比版，被 balanced 78 条取代）。",
        "event_date": "2026-08-12",
        "as_of": "2026-08-14",
        "operative_status": "SUPERSEDED",
        "timeline": ["不平衡版: 2026-08-12", "balanced 取代: T049"],
        "authority": "T1",
        "provenance": "manual",
    },
    {
        "anchor_id": "MAN-011",
        "source_type": "report",
        "candidate_path": "reports/r3/r3a_zeroshot_stale_check.json",
        "evidence_excerpt": "R3A 0-shot STALE 对照：stale_accuracy=0.35（Base 无 LoRA）。",
        "event_date": "2026-08-14",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["0-shot 对照: 2026-08-14", "Base 能力基线"],
        "authority": "T3",
        "provenance": "manual",
    },
    {
        "anchor_id": "MAN-012",
        "source_type": "model_weights",
        "candidate_path": "models/qxen_first_milestone/adapters.safetensors",
        "evidence_excerpt": "QXEN first milestone adapter（早期里程碑产物）。",
        "event_date": "2026-08-11",
        "as_of": "2026-08-14",
        "operative_status": "SUPERSEDED",
        "timeline": ["first milestone: 2026-08-11", "后续 R1/R3 取代"],
        "authority": "T1",
        "provenance": "manual",
    },
    {
        "anchor_id": "MAN-013",
        "source_type": "data_file",
        "candidate_path": "data/r3/real_timeline/fresh.jsonl",
        "evidence_excerpt": "real_timeline fresh 12 条（冻结评估专用）。",
        "event_date": "2026-08-13",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["real fresh 冻结: 2026-08-13"],
        "authority": "T1",
        "provenance": "manual",
    },
    {
        "anchor_id": "MAN-014",
        "source_type": "doc",
        "candidate_path": "调度状态/QWEN蒸馏上下文_codex_kimi.md",
        "evidence_excerpt": "金融模型及数据 target workspace 蒸馏上下文（三策略整合待续做）。",
        "event_date": "2026-08-11",
        "as_of": "2026-08-14",
        "operative_status": "CURRENT",
        "timeline": ["蒸馏上下文: 2026-08-11", "target workspace 入口"],
        "authority": "T2",
        "provenance": "manual",
    },
]


# state_patch 验证集（从任务账本真实状态变迁抽取，人工校验后固化）
STATE_PATCH_SAMPLES = [
    {
        "sample_id": "SP-001",
        "task_type": "state_patch",
        "old_state": {"phaseB_adapter": "active", "source": "phaseB 687 条"},
        "new_event": "T054 门控评估 FAIL（5/7 未达标）",
        "patch": {"supersede_evidence": ["phaseB"], "add_finding": ["phaseB FAIL 冻结，回退 mixed"]},
        "expected_ops": ["SUPERSEDE_EVIDENCE", "ADD_FINDING"],
        "provenance": "trajectory",
        "source": "任务账本 T054",
    },
    {
        "sample_id": "SP-002",
        "task_type": "state_patch",
        "old_state": {"ctxA_adapter": "active", "source": "ctxA 108 条"},
        "new_event": "T049 修正 DROP 过度占比 108→78 条",
        "patch": {"update_element": [{"element_id": "DROP", "status": "BALANCED"}], "add_evidence": ["train_balanced"]},
        "expected_ops": ["UPDATE_ELEMENT", "ADD_EVIDENCE"],
        "provenance": "trajectory",
        "source": "任务账本 T049",
    },
    {
        "sample_id": "SP-003",
        "task_type": "state_patch",
        "old_state": {"r3a_synth": "active", "source": "R3A 合成时间线 v5"},
        "new_event": "v5 Gate FAIL，STALE 负迁移 35%→15.6%",
        "patch": {"supersede_evidence": ["r3a_cot_v5"], "add_finding": ["合成主线冻结"], "preserve_rule": ["R3A 冻结资产"]},
        "expected_ops": ["SUPERSEDE_EVIDENCE", "ADD_FINDING", "PRESERVE_RULE"],
        "provenance": "trajectory",
        "source": "冻结报告 r3a_synthetic_freeze.md",
    },
    {
        "sample_id": "SP-004",
        "task_type": "state_patch",
        "old_state": {"ec_v1": "trained", "source": "pool 20 条 LoRA 40 iters"},
        "new_event": "19/20 parse = 过拟合假象判定",
        "patch": {"add_finding": ["ec_v1 归档 T001 快照"], "preserve_rule": ["不 resume 不作种子"]},
        "expected_ops": ["ADD_FINDING", "PRESERVE_RULE"],
        "provenance": "trajectory",
        "source": "REVISION 0.2 / ec_v1 ARCHIVED.md",
    },
    {
        "sample_id": "SP-005",
        "task_type": "state_patch",
        "old_state": {"skill_7phase": "active", "source": "旧 7 阶段 skill"},
        "new_event": "Kimi-Expert redefine 统一路线",
        "patch": {"supersede_evidence": ["旧 skill"], "add_finding": ["统一路线 skill"], "preserve_rule": ["冻结资产"]},
        "expected_ops": ["SUPERSEDE_EVIDENCE", "ADD_FINDING", "PRESERVE_RULE"],
        "provenance": "manual",
        "source": "redefine 2026-08-15",
    },
    {
        "sample_id": "SP-006",
        "task_type": "state_patch",
        "old_state": {"r3a_v4": "active", "source": "字段隔离契约 v4"},
        "new_event": "v5 取代 v4（isolated 契约下 v5 优于 v4）",
        "patch": {"supersede_evidence": ["r3a_cot_v4"], "add_evidence": ["r3a_cot_v5"]},
        "expected_ops": ["SUPERSEDE_EVIDENCE", "ADD_EVIDENCE"],
        "provenance": "trajectory",
        "source": "任务账本/评估报告",
    },
    {
        "sample_id": "SP-007",
        "task_type": "state_patch",
        "old_state": {"hq1700": "active", "source": "HQ1700 1700 条 7 标签"},
        "new_event": "T051 门控 FAIL → T052 混合训练修复 PASS",
        "patch": {"supersede_evidence": ["hq1700"], "add_evidence": ["mixed_train 477 条"]},
        "expected_ops": ["SUPERSEDE_EVIDENCE", "ADD_EVIDENCE"],
        "provenance": "trajectory",
        "source": "任务账本 T051/T052",
    },
    {
        "sample_id": "SP-008",
        "task_type": "state_patch",
        "old_state": {"三策略看板": "active", "source": "三策略版主脚本"},
        "new_event": "两策略备份归档（.bak_ 后缀）",
        "patch": {"dedup": ["两策略备份"], "preserve_rule": ["当前生效版"]},
        "expected_ops": ["DEDUP", "PRESERVE_RULE"],
        "provenance": "external_real",
        "source": "三策略每日看板目录",
    },
    {
        "sample_id": "SP-009",
        "task_type": "state_patch",
        "old_state": {"R3A gate test": "active", "source": "eval_pool 192 v6"},
        "new_event": "合成主线冻结 → 停止使用",
        "patch": {"add_finding": ["gate test 冻结"], "preserve_rule": ["评估协议不变"]},
        "expected_ops": ["ADD_FINDING", "PRESERVE_RULE"],
        "provenance": "trajectory",
        "source": "冻结报告",
    },
    {
        "sample_id": "SP-010",
        "task_type": "state_patch",
        "old_state": {"r1_balanced": "active", "source": "R1 平衡数据"},
        "new_event": "replay 构建使用该数据",
        "patch": {"add_evidence": ["train.jsonl"], "preserve_rule": ["fresh test 不得进 replay"]},
        "expected_ops": ["ADD_EVIDENCE", "PRESERVE_RULE"],
        "provenance": "derived",
        "source": "real_timeline",
    },
    {
        "sample_id": "SP-011",
        "task_type": "state_patch",
        "old_state": {"训练权重": "active", "source": "r1 recall 最终权重"},
        "new_event": "0000050 周期 checkpoint 被最终权重取代",
        "patch": {"supersede_evidence": ["0000050_checkpoint"], "add_evidence": ["adapters.safetensors"]},
        "expected_ops": ["SUPERSEDE_EVIDENCE", "ADD_EVIDENCE"],
        "provenance": "trajectory",
        "source": "TR-06 标注",
    },
    {
        "sample_id": "SP-012",
        "task_type": "state_patch",
        "old_state": {"r1_recall": "active", "source": "R1 recall 修复"},
        "new_event": "T058 确认 R1 正式产物 + 门控 PASS",
        "patch": {"update_element": [{"element_id": "R1", "status": "VERIFIED"}]},
        "expected_ops": ["UPDATE_ELEMENT"],
        "provenance": "trajectory",
        "source": "任务账本 T058",
    },
    {
        "sample_id": "SP-013",
        "task_type": "state_patch",
        "old_state": {"distill_ctxA": "active", "source": "DROP 45.4%"},
        "new_event": "DROP 过度占比修正为 24.4%",
        "patch": {"update_element": [{"element_id": "DROP", "status": "REBALANCED"}]},
        "expected_ops": ["UPDATE_ELEMENT"],
        "provenance": "trajectory",
        "source": "任务账本 T049",
    },
    {
        "sample_id": "SP-014",
        "task_type": "state_patch",
        "old_state": {"r3a_cot_v4": "active", "source": "legacy 契约"},
        "new_event": "契约切换字段隔离（v5）",
        "patch": {"supersede_evidence": ["v4_contract"], "add_finding": ["isolated 契约"]},
        "expected_ops": ["SUPERSEDE_EVIDENCE", "ADD_FINDING"],
        "provenance": "trajectory",
        "source": "v4→v5 评估报告",
    },
    {
        "sample_id": "SP-015",
        "task_type": "state_patch",
        "old_state": {"real_timeline": "active", "source": "12 锚点"},
        "new_event": "数据扩充 100 档（用户授权）",
        "patch": {"add_evidence": ["external 8 + trajectory 13 + derived 15 + manual 14"], "preserve_rule": ["fresh 分层"]},
        "expected_ops": ["ADD_EVIDENCE", "PRESERVE_RULE"],
        "provenance": "manual",
        "source": "数据缺口分析",
    },
    {
        "sample_id": "SP-016",
        "task_type": "state_patch",
        "old_state": {"ec_v1 pool": "active", "source": "20 条"},
        "new_event": "统一路线数据 100 档",
        "patch": {"update_element": [{"element_id": "pool", "status": "EXPANDED"}], "dedup": ["重复胶囊"]},
        "expected_ops": ["UPDATE_ELEMENT", "DEDUP"],
        "provenance": "manual",
        "source": "T001 数据扩充",
    },
    {
        "sample_id": "SP-017",
        "task_type": "state_patch",
        "old_state": {"三策略看板": "active", "source": "主脚本 2947 行"},
        "new_event": "两策略备份归档",
        "patch": {"supersede_evidence": ["bak_两策略改现金鎏金"], "preserve_rule": ["三策略主脚本"]},
        "expected_ops": ["SUPERSEDE_EVIDENCE", "PRESERVE_RULE"],
        "provenance": "external_real",
        "source": "三策略每日看板目录",
    },
    {
        "sample_id": "SP-018",
        "task_type": "state_patch",
        "old_state": {"r3a_structured_v3": "active", "source": "结构化 v3"},
        "new_event": "统一路线取代旧多 adapter 范式",
        "patch": {"supersede_evidence": ["r3a_*"], "add_finding": ["qxen_joint_v1 唯一 adapter"]},
        "expected_ops": ["SUPERSEDE_EVIDENCE", "ADD_FINDING"],
        "provenance": "trajectory",
        "source": "redefine 2026-08-15",
    },
    {
        "sample_id": "SP-019",
        "task_type": "state_patch",
        "old_state": {"r1_recall_test": "active", "source": "test_fresh 540"},
        "new_event": "评估协议确认",
        "patch": {"preserve_rule": ["fresh test 不得进 replay"], "add_evidence": ["r11 全指标 1.0000"]},
        "expected_ops": ["PRESERVE_RULE", "ADD_EVIDENCE"],
        "provenance": "derived",
        "source": "real_timeline",
    },
    {
        "sample_id": "SP-020",
        "task_type": "state_patch",
        "old_state": {"循环工作": "active", "source": "working loop"},
        "new_event": "T001 数据扩充执行",
        "patch": {"update_element": [{"element_id": "T001", "status": "EXECUTING"}], "preserve_rule": ["冻结资产"]},
        "expected_ops": ["UPDATE_ELEMENT", "PRESERVE_RULE"],
        "provenance": "manual",
        "source": "dispatch",
    },
    {
        "sample_id": "SP-021",
        "task_type": "state_patch",
        "old_state": {"r3a_realistic_gate": "active", "source": "192 条 eval"},
        "new_event": "v5 conflict 20 条全对",
        "patch": {"add_evidence": ["conflict20 全对"], "add_finding": ["显式冲突非瓶颈"]},
        "expected_ops": ["ADD_EVIDENCE", "ADD_FINDING"],
        "provenance": "trajectory",
        "source": "冻结报告",
    },
    {
        "sample_id": "SP-022",
        "task_type": "state_patch",
        "old_state": {"r3a_v6": "active", "source": "v6 语义标注"},
        "new_event": "v6 标注仅反转错误方向，STALE 15.6% 不变",
        "patch": {"add_finding": ["v6 标注失效"], "supersede_evidence": ["v6 标注数据"]},
        "expected_ops": ["ADD_FINDING", "SUPERSEDE_EVIDENCE"],
        "provenance": "trajectory",
        "source": "冻结报告",
    },
    {
        "sample_id": "SP-023",
        "task_type": "state_patch",
        "old_state": {"r3_pipeline": "active", "source": "R3 流水线"},
        "new_event": "R3A Gate FAIL → 转向 ec_v1",
        "patch": {"reopen_finding": ["R3A"], "add_finding": ["Evidence Capsule 路线"]},
        "expected_ops": ["REOPEN_FINDING", "ADD_FINDING"],
        "provenance": "trajectory",
        "source": "会话历史",
    },
    {
        "sample_id": "SP-024",
        "task_type": "state_patch",
        "old_state": {"三策略每日看板": "active", "source": "v 备份"},
        "new_event": "现金鎏金备份",
        "patch": {"dedup": ["现金鎏金备份"]},
        "expected_ops": ["DEDUP"],
        "provenance": "external_real",
        "source": "三策略看板备份",
    },
    {
        "sample_id": "SP-025",
        "task_type": "state_patch",
        "old_state": {"r1_selected": "active", "source": "R1 正式产物"},
        "new_event": "门控指标 PASS 确认",
        "patch": {"update_element": [{"element_id": "R1", "status": "SELECTED"}], "preserve_rule": ["门控协议"]},
        "expected_ops": ["UPDATE_ELEMENT", "PRESERVE_RULE"],
        "provenance": "trajectory",
        "source": "任务账本 T058",
    },
    {
        "sample_id": "SP-026",
        "task_type": "state_patch",
        "old_state": {"data100": "planned", "source": "数据扩充"},
        "new_event": "capsule 100 档分层",
        "patch": {"add_evidence": ["train 80 + fresh 20"], "preserve_rule": ["fresh 零重叠"]},
        "expected_ops": ["ADD_EVIDENCE", "PRESERVE_RULE"],
        "provenance": "manual",
        "source": "T001",
    },
    {
        "sample_id": "SP-027",
        "task_type": "state_patch",
        "old_state": {"r3a_rule_shadow": "active", "source": "规则影子"},
        "new_event": "规则兜底确定化",
        "patch": {"preserve_rule": ["schema 校验/链校验/冲突校验"], "add_finding": ["R4/R5/R7 不训练"]},
        "expected_ops": ["PRESERVE_RULE", "ADD_FINDING"],
        "provenance": "manual",
        "source": "统一路线 skill §8",
    },
    {
        "sample_id": "SP-028",
        "task_type": "state_patch",
        "old_state": {"qwen_distiller": "active", "source": "distiller skill"},
        "new_event": "Evidence Capsule sub-agent 转向",
        "patch": {"update_element": [{"element_id": "QXEN-CD", "status": "REDIRECTED"}], "preserve_rule": ["蒸馏纪律"]},
        "expected_ops": ["UPDATE_ELEMENT", "PRESERVE_RULE"],
        "provenance": "manual",
        "source": "用户授权重构",
    },
    {
        "sample_id": "SP-029",
        "task_type": "state_patch",
        "old_state": {"r3a_calib_v1": "active", "source": "校准 v1"},
        "new_event": "校准 v1 被取代",
        "patch": {"supersede_evidence": ["r3a_calib_v1"], "add_evidence": ["统一路线"]},
        "expected_ops": ["SUPERSEDE_EVIDENCE", "ADD_EVIDENCE"],
        "provenance": "trajectory",
        "source": "models/_archive",
    },
    {
        "sample_id": "SP-030",
        "task_type": "state_patch",
        "old_state": {"r3a_structured_v1": "active", "source": "结构化 v1"},
        "new_event": "结构化 v1 被取代",
        "patch": {"supersede_evidence": ["r3a_structured_v1"], "add_evidence": ["统一路线"]},
        "expected_ops": ["SUPERSEDE_EVIDENCE", "ADD_EVIDENCE"],
        "provenance": "trajectory",
        "source": "models/_archive",
    },
    {
        "sample_id": "SP-031",
        "task_type": "state_patch",
        "old_state": {"r3a_hard_v1": "active", "source": "hard v1"},
        "new_event": "hard v1 被取代",
        "patch": {"supersede_evidence": ["r3a_hard_v1"], "add_evidence": ["统一路线"]},
        "expected_ops": ["SUPERSEDE_EVIDENCE", "ADD_EVIDENCE"],
        "provenance": "trajectory",
        "source": "models/_archive",
    },
    {
        "sample_id": "SP-032",
        "task_type": "state_patch",
        "old_state": {"r3a_v2": "active", "source": "r3a v2"},
        "new_event": "v2 被取代",
        "patch": {"supersede_evidence": ["r3a_v2"], "add_evidence": ["统一路线"]},
        "expected_ops": ["SUPERSEDE_EVIDENCE", "ADD_EVIDENCE"],
        "provenance": "trajectory",
        "source": "models/_archive",
    },
    {
        "sample_id": "SP-033",
        "task_type": "state_patch",
        "old_state": {"r3a_hard_pure_v1": "active", "source": "hard pure v1"},
        "new_event": "hard pure v1 被取代",
        "patch": {"supersede_evidence": ["r3a_hard_pure_v1"], "add_evidence": ["统一路线"]},
        "expected_ops": ["SUPERSEDE_EVIDENCE", "ADD_EVIDENCE"],
        "provenance": "trajectory",
        "source": "models/_archive",
    },
    {
        "sample_id": "SP-034",
        "task_type": "state_patch",
        "old_state": {"r3a_cot_v4": "active", "source": "cot v4"},
        "new_event": "cot v4 被取代",
        "patch": {"supersede_evidence": ["r3a_cot_v4"], "add_evidence": ["统一路线"]},
        "expected_ops": ["SUPERSEDE_EVIDENCE", "ADD_EVIDENCE"],
        "provenance": "trajectory",
        "source": "models/_archive",
    },
    {
        "sample_id": "SP-035",
        "task_type": "state_patch",
        "old_state": {"r3a_structured_v2": "active", "source": "结构化 v2"},
        "new_event": "结构化 v2 被取代",
        "patch": {"supersede_evidence": ["r3a_structured_v2"], "add_evidence": ["统一路线"]},
        "expected_ops": ["SUPERSEDE_EVIDENCE", "ADD_EVIDENCE"],
        "provenance": "trajectory",
        "source": "models/_archive",
    },
    {
        "sample_id": "SP-036",
        "task_type": "state_patch",
        "old_state": {"r3a_structured_v3": "active", "source": "结构化 v3"},
        "new_event": "结构化 v3 被取代",
        "patch": {"supersede_evidence": ["r3a_structured_v3"], "add_evidence": ["统一路线"]},
        "expected_ops": ["SUPERSEDE_EVIDENCE", "ADD_EVIDENCE"],
        "provenance": "trajectory",
        "source": "models/_archive",
    },
    {
        "sample_id": "SP-037",
        "task_type": "state_patch",
        "old_state": {"r3a_hard_v2": "active", "source": "hard v2"},
        "new_event": "hard v2 被取代",
        "patch": {"supersede_evidence": ["r3a_hard_v2"], "add_evidence": ["统一路线"]},
        "expected_ops": ["SUPERSEDE_EVIDENCE", "ADD_EVIDENCE"],
        "provenance": "trajectory",
        "source": "models/_archive",
    },
    {
        "sample_id": "SP-038",
        "task_type": "state_patch",
        "old_state": {"r3a_hard_pure_v1_resume1000": "active", "source": "hard pure resume1000"},
        "new_event": "resume1000 被取代",
        "patch": {"supersede_evidence": ["r3a_hard_pure_v1_resume1000"], "add_evidence": ["统一路线"]},
        "expected_ops": ["SUPERSEDE_EVIDENCE", "ADD_EVIDENCE"],
        "provenance": "trajectory",
        "source": "models/_archive",
    },
    {
        "sample_id": "SP-039",
        "task_type": "state_patch",
        "old_state": {"r3a_hard_v1_seq256": "active", "source": "hard v1 seq256"},
        "new_event": "seq256 被取代",
        "patch": {"supersede_evidence": ["r3a_hard_v1_seq256"], "add_evidence": ["统一路线"]},
        "expected_ops": ["SUPERSEDE_EVIDENCE", "ADD_EVIDENCE"],
        "provenance": "trajectory",
        "source": "models/_archive",
    },
    {
        "sample_id": "SP-040",
        "task_type": "state_patch",
        "old_state": {"r3a_calib_v1_retry": "active", "source": "calib v1 retry"},
        "new_event": "calib retry 被取代",
        "patch": {"supersede_evidence": ["r3a_calib_v1_retry"], "add_evidence": ["统一路线"]},
        "expected_ops": ["SUPERSEDE_EVIDENCE", "ADD_EVIDENCE"],
        "provenance": "trajectory",
        "source": "models/_archive",
    },
    {
        "sample_id": "SP-041",
        "task_type": "state_patch",
        "old_state": {"r3a_cot_v5": "active", "source": "cot v5"},
        "new_event": "v5 Gate FAIL 冻结",
        "patch": {"supersede_evidence": ["r3a_cot_v5"], "add_finding": ["合成主线冻结"], "preserve_rule": ["冻结资产只读"]},
        "expected_ops": ["SUPERSEDE_EVIDENCE", "ADD_FINDING", "PRESERVE_RULE"],
        "provenance": "trajectory",
        "source": "冻结报告",
    },
    {
        "sample_id": "SP-042",
        "task_type": "state_patch",
        "old_state": {"r3_pipeline": "active", "source": "R3 流水线 r3a/r3b/r3c"},
        "new_event": "R3B/R3C 并入胶囊契约",
        "patch": {"update_element": [{"element_id": "R3B", "status": "MERGED"}, {"element_id": "R3C", "status": "MERGED"}]},
        "expected_ops": ["UPDATE_ELEMENT"],
        "provenance": "manual",
        "source": "统一路线 skill §0.4",
    },
    {
        "sample_id": "SP-043",
        "task_type": "state_patch",
        "old_state": {"r3a_gate_test": "active", "source": "r3a_gate_test 数据集"},
        "new_event": "冻结资产清单确认",
        "patch": {"preserve_rule": ["r3a_gate_test_ext 只读"]},
        "expected_ops": ["PRESERVE_RULE"],
        "provenance": "trajectory",
        "source": "冻结报告",
    },
    {
        "sample_id": "SP-044",
        "task_type": "state_patch",
        "old_state": {"r1_recall": "active", "source": "R1 recall 修复"},
        "new_event": "R1 门控 PASS",
        "patch": {"update_element": [{"element_id": "R1", "status": "PASS"}]},
        "expected_ops": ["UPDATE_ELEMENT"],
        "provenance": "trajectory",
        "source": "任务账本 T058",
    },
    {
        "sample_id": "SP-045",
        "task_type": "state_patch",
        "old_state": {"训练配置": "active", "source": "r3_training.yaml"},
        "new_event": "LoRA 训练配置沿范",
        "patch": {"preserve_rule": ["rank8/lr4e-6/epochs 小步"]},
        "expected_ops": ["PRESERVE_RULE"],
        "provenance": "manual",
        "source": "skill §5",
    },
    {
        "sample_id": "SP-046",
        "task_type": "state_patch",
        "old_state": {"数据": "active", "source": "pool 20"},
        "new_event": "数据扩充到 100",
        "patch": {"add_evidence": ["external 8 + trajectory 13 + derived 15 + manual 14"]},
        "expected_ops": ["ADD_EVIDENCE"],
        "provenance": "manual",
        "source": "T001",
    },
    {
        "sample_id": "SP-047",
        "task_type": "state_patch",
        "old_state": {"训练数据": "active", "source": "capsule"},
        "new_event": "task_type 分流",
        "patch": {"update_element": [{"element_id": "task_type", "status": "SPLIT"}]},
        "expected_ops": ["UPDATE_ELEMENT"],
        "provenance": "manual",
        "source": "skill §4",
    },
    {
        "sample_id": "SP-048",
        "task_type": "state_patch",
        "old_state": {"评估": "active", "source": "single layer"},
        "new_event": "双层 Gate",
        "patch": {"add_finding": ["e2e 晋级门槛"], "preserve_rule": ["invalid_output=0"]},
        "expected_ops": ["ADD_FINDING", "PRESERVE_RULE"],
        "provenance": "manual",
        "source": "skill §6",
    },
    {
        "sample_id": "SP-049",
        "task_type": "state_patch",
        "old_state": {"r3a_ab_test": "active", "source": "AB 测试"},
        "new_event": "AB 测试结论",
        "patch": {"add_finding": ["AB 结论落盘"], "preserve_rule": ["评估协议"]},
        "expected_ops": ["ADD_FINDING", "PRESERVE_RULE"],
        "provenance": "trajectory",
        "source": "r3a_ab_test_result.md",
    },
    {
        "sample_id": "SP-050",
        "task_type": "state_patch",
        "old_state": {"蒸馏上下文": "active", "source": "codex/kimi 会话"},
        "new_event": "蒸馏上下文落盘",
        "patch": {"add_evidence": ["QWEN蒸馏上下文_codex_kimi.md"], "preserve_rule": ["target workspace 只读"]},
        "expected_ops": ["ADD_EVIDENCE", "PRESERVE_RULE"],
        "provenance": "manual",
        "source": "交接文档",
    },
]


def capsule_from(anchor: dict, src_pool_capsule: dict | None = None) -> dict:
    """从锚点构造 capsule 样本（统一契约格式）。"""
    if src_pool_capsule is not None:
        # 复用 pool capsule 的内容字段
        return dict(src_pool_capsule)
    cand = anchor.get("candidate_path", "")
    return {
        "capsule_id": f"EC-{anchor['anchor_id']}",
        "source_type": anchor.get("source_type", "other"),
        "relevance": "high",
        "key_evidence": [{"text": anchor.get("evidence_excerpt", ""), "source": cand, "preserve_verbatim": True}],
        "timeline": anchor.get("timeline", []),
        "relations": anchor.get("relations", []),
        "conflicts": [],
        "uncertainty": [],
        "immutable_fields": ["来源路径", "哈希", "证据摘录", "日期"],
        "compressible": [],
        "sufficiency": "sufficient",
        "next_step": "",
        "reference": [cand],
        "metadata": {
            "model": "r2r7-data-expansion",
            "contract_version": "v1",
            "as_of": anchor.get("as_of"),
        },
        "anchor_id": anchor["anchor_id"],
        "event_date": anchor.get("event_date"),
        "operative_status": anchor.get("operative_status"),
        "authority": anchor.get("authority"),
        "provenance": anchor.get("provenance", "manual"),
    }


def _tag(rows: list[dict], provenance: str, task_type: str = "capsule") -> list[dict]:
    """统一打标签：provenance + task_type + split 来源。"""
    out = []
    for r in rows:
        r = dict(r)
        r["provenance"] = provenance
        r["task_type"] = task_type
        r["data_source"] = provenance
        out.append(r)
    return out


def main() -> int:
    pool = load_jsonl(POOL)
    if not pool:
        print("ERROR: pool empty")
        return 1

    # 1. 现有 pool 20 条（provenance 保留池内标注：real_anchor / manual_annotated，
    #    统一来源标记 existing，供 fresh/train 分层判断）
    existing_real, existing_manual = [], []
    for c in pool:
        c = dict(c)
        src = c.get("provenance", "")
        if src == "real_anchor":
            existing_real.append(c)
        else:
            existing_manual.append(c)
    existing_real = _tag(existing_real, "existing_real", "capsule")
    existing_manual = _tag(existing_manual, "existing_manual", "capsule")

    # 2. 外部真实材料 8 条（真实锚点 → fresh）
    external = _tag([capsule_from(a) for a in EXTERNAL_ANCHORS], "external_real", "capsule")

    # 3. 轨迹挖掘 capsule 43 条（任务账本真实里程碑，审核后固化）
    trajectory = _tag([capsule_from(a) for a in TRAJECTORY_CAPSULES], "trajectory", "capsule")

    # 4. derived 样本 15 条
    derived = _tag([capsule_from(a) for a in DERIVED_ANCHORS], "derived", "capsule")

    # 5. 人工构造 14 条
    manual = _tag([capsule_from(a) for a in MANUAL_CAPSULES], "manual", "capsule")

    # 6. state_patch 验证集 50 条（task_type=state_patch）
    state_patch = []
    for s in STATE_PATCH_SAMPLES:
        r = dict(s)
        r["task_type"] = "state_patch"
        r["data_source"] = r.get("provenance", "manual")
        state_patch.append(r)

    # ---------- capsule 分层 ----------
    # fresh 只放真实锚点：existing_real 12 + external 8 = 20
    fresh = existing_real + external
    # train 为其余全部：existing_manual 8 + trajectory 43 + derived 15 + manual 14 = 80
    train = existing_manual + trajectory + derived + manual

    all_capsules = existing_real + existing_manual + external + trajectory + derived + manual
    capsule_ids = [c["capsule_id"] for c in all_capsules]
    dup_ids = {i for i in capsule_ids if capsule_ids.count(i) > 1}
    if dup_ids:
        print(f"ERROR: duplicate capsule_ids: {sorted(dup_ids)}")
        return 1

    if len(fresh) != 20:
        print(f"ERROR: fresh 应为 20，实际 {len(fresh)}")
        return 1
    if len(train) != 80:
        print(f"ERROR: train 应为 80，实际 {len(train)}")
        return 1
    fresh_ids = {c["capsule_id"] for c in fresh}
    train_ids = {c["capsule_id"] for c in train}
    overlap = fresh_ids & train_ids
    if overlap:
        print(f"ERROR: fresh/train 重叠: {overlap}")
        return 1
    if len(fresh_ids) != 20 or len(train_ids) != 80:
        print("ERROR: capsule_id 非唯一")
        return 1
    if not (50 <= len(state_patch) <= 50):
        print(f"ERROR: state_patch 应为 50，实际 {len(state_patch)}")
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    def write(path: Path, rows: list[dict]) -> None:
        path.write_text(
            "".join(json.dumps(r, ensure_ascii=False) + "\n" for r in rows), encoding="utf-8"
        )

    write(OUT_DIR / "train_capsule.jsonl", train)
    write(OUT_DIR / "fresh_capsule.jsonl", fresh)
    write(OUT_DIR / "state_patch_validation.jsonl", state_patch)

    # ---------- manifest ----------
    def counts_by(rows: list[dict], key: str) -> dict:
        d = {}
        for r in rows:
            v = r.get(key, "unknown")
            if isinstance(v, (list, dict)):
                v = json.dumps(v, ensure_ascii=False, sort_keys=True)
            d[v] = d.get(v, 0) + 1
        return dict(sorted(d.items()))

    manifest = {
        "stage": "R2-R7-data-expansion-DONE",
        "created_at": "2026-08-14",
        "target_workspace": "金融模型及数据（只读）",
        "task_type": {"capsule": 100, "state_patch": len(state_patch)},
        "split": {
            "train_capsule": len(train),
            "fresh_capsule": len(fresh),
        },
        "train_by_provenance": counts_by(train, "provenance"),
        "fresh_by_provenance": counts_by(fresh, "provenance"),
        "train_by_status": counts_by(train, "operative_status"),
        "fresh_by_status": counts_by(fresh, "operative_status"),
        "state_patch_by_ops": counts_by(state_patch, "expected_ops"),
        "fresh_only_real_anchor": True,
        "zero_overlap_fresh_train": True,
        "frozen_assets_untouched": ["models/_archive/", "金融模型及数据/"],
        "skill_untouched": ["QXEN_R2_R7_UNIFIED_ROUTE_SKILL.md"],
        "files": {
            "train": "data/r3/ec_v1/data100/train_capsule.jsonl",
            "fresh": "data/r3/ec_v1/data100/fresh_capsule.jsonl",
            "state_patch": "data/r3/ec_v1/data100/state_patch_validation.jsonl",
        },
        "next": "验收通过后进入 qxen_joint_v1 联合训练（skill §5），本阶段不启动训练",
    }
    write(OUT_DIR / "manifest.json", [manifest])

    print(json.dumps(manifest, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
